# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f2f6dc3f37a2a41e871116bf3eaeeba246e5067035af0e7da748601c9ed9f908a967cc0394f0e0f42a3b12e57f52d85cd15442b7bdacd0265c3cab203764067

test:
  secret_key_base: cdee12d64b8d93fe5c6c7056ec956d10e208ebb70193ec3253c62bba673604cc7eaebfc97db8d24bec055df5c3bb779e6e2db33e57b9447d651cc9ce63add37f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
